
GIMPTOOL=wine64 /usr/x86_64-w64-mingw32/sys-root/mingw/bin/gimptool-2.0.exe

CC=x86_64-w64-mingw32-gcc
CFLAGS=-pipe -O2 -g -Wall $(shell x86_64-w64-mingw32-pkg-config --cflags gtk+-2.0 gtkglext-1.0 gimp-2.0 glew)
LDFLAGS=-mwindows

EXT=.exe

TARGET=normalmap$(EXT)

LIBS=$(shell x86_64-w64-mingw32-pkg-config --libs gtk+-2.0 gtkglext-1.0 gimp-2.0 gimpui-2.0 glew) -lm
